# Generated by Django 3.1.7 on 2021-04-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='line_id',
            field=models.CharField(default='Chinese', max_length=10),
            preserve_default=False,
        ),
    ]
